# Generated by Django 5.0.14 on 2026-09-17 11:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=150)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('hospital_name', models.CharField(max_length=150)),
                ('location', models.CharField(help_text='Hospital city / area', max_length=100)),
                ('required_date', models.DateField()),
                ('bags_required', models.PositiveIntegerField(help_text='Number of blood bags needed', validators=[django.core.validators.MinValueValidator(1)])),
                ('contact_number', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (9-15 digits, optionally starting with +).', regex='^\\+?\\d{9,15}$')])),
                ('description', models.TextField(blank=True, help_text='Reason / additional details', max_length=500)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('phone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (9-15 digits, optionally starting with +).', regex='^\\+?\\d{9,15}$')])),
                ('location', models.CharField(help_text='City / area, e.g. Feni', max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True, help_text='Uncheck this if you are currently unable to donate.')),
                ('description', models.TextField(blank=True, help_text='A short note about yourself (optional).', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
